### ISSUE TITLE
[Talk Proposal] ZeroNet - A decentralized censorship-resistant network

### ISSUE THREAD

**Issue by rllola** [francep2p/community#57]
#### Title

ZeroNet - A decentralized censorship-resistant network

#### Languages

- [x] 🇫🇷
- [x] 🇬🇧

#### Estimated duration

~20 min

#### Required knowledge level
  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [x] None     | [ ] None     |
| [x] Beginner | [x] Beginner | [ ] Beginner | [x] Beginner |
| [ ] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory) 
- [ ] Yes (if possible) 
- [x] No 

---

## Description of your talk

This talk will be an introduction to ZeroNet. It will introduce the idea behind it and some technicals specificities and stay beginner friendly at the same time.

ZeroNet is an open source project already being used by thousands of people in the world. It is a dedicated network which is censorship resistant and allow users to share content without a central form of censorship.

---

## About you

* Name: Lola Rigaut-Luczak 
* Matrix handle: None
* Discord handle: None
* Other contact info: me@laflemme.lol
* Links to your previous talks: None
* Other (your projects, etc...): https://github.com/rllola
* Availability (monthly number, date): 4/12/2019 - 01/02/2020

**Comment by George-Soros** [comment]
**"share content without a central form of censorship"** this not true entirely! I can demonstrate that minimum 15 times I was censored on GitHub because I reported very embarrassing thing about ZeroNet. 

Do you know @rllola that the ZeroNet software violating for years many licenses namely AGPL3+, Apache 2.0 and GPLv3? As a result the GPLv2 license of ZeroNet is terminated! 
I was who reported this and currently there is a voting about the "new" license. 

Also worth to note that I had a pull request which is closed by @HelloZeroNet and merged my commit in his own name! What kind of person do this? Seriously. 

ZeroNet is very centralized and it is subject of abuse by Hungarian fascists from Budapest. They attacked me not only because I reported problems around the illegal distribution of ZeroNet but also because my username was on GitHub @antifa which thank to this right-wingers are suspended. 

So tell me now that ZeroNet is censorship resistant or that is decentralized. They them self censoring GitHub which is very centralized. 

You in the other hand @rllola deserve to be helped. I see your work and I think you are a genius! :clap:

**Comment by George-Soros** [comment]
I strongly suggest **stop distributing ZeroNet** until it is not having a GPLv3+ license! If you distribute it you are directly and knowingly committing a crime! 
It is illegal to distribute ZeroNet in its current form I'm sure that is in France too!

**Comment by gorhgorh** [comment]
contrepoint interessant @George-Soros par contre le compte throwaway crée deux heure avant le commnentaire ne lui donne pas trop de poids, mais on pourra en discuter au prochain event ? :)

**Comment by George-Soros** [comment]
![bolton](https://user-images.githubusercontent.com/57743911/68840705-26555900-06bb-11ea-8180-8c257ec26529.gif)

**Comment by gorhgorh** [comment]
merci de confirmer ce que je pensais =)

**Comment by George-Soros** [comment]
@gorhgorh My account @antifa has suspended because Hungarian neo-Nazis from Budapest attacked me for reporting years long license violations and copyright infringement in ZeroNet.

**Comment by George-Soros** [comment]
@gorhgorh Mon compte @antifa a été suspendu parce que des néo-nazis hongrois de Budapest m'ont attaqué pour avoir signalé des violations de licence et de copyright pendant plusieurs années dans ZeroNet.

ZeroNet est dirigé par un fasciste hongrois.

**Comment by gorhgorh** [comment]
I see,
I'll have to look at the history of this project more thoroughly, and thanks for these informations.
Decentralisation movement is attracting lots of different actors, not always for the better.

I'm also interested in @rllola point of view on the question ?

**Comment by George-Soros** [comment]
ZeroNet is great but is illegal in its current form! Not possible to distribute it publicly or in some countries you can get into real trouble for it. If the license up GPLv3 in your repository you are free to distribute it. 

Some people like @imachug even **tried to claim proprietary rights** over ZeroNet! This is a real destructive threat just as the Hungarian neo-Nazis in Budapest who claim that ZeroNet is developed in Budapest which is false. Many people, including myself contributed to ZeroNet. 

I like ZeroNet but again, IF the license in your fork is not GPLv3(+) you are not allowed to distribute it publicly! There was also various attempt in this very moment to get rid of many libraries and LIMIT ZeroNet in order to avoid GPLv3+. Very very problematic in this moment ZeroNet. Censoring GitHub, merging pull request without giving credit to the originator, violating licenses and copyrights etc. 

@rllola can use a GPLv3 license in her repository and distribute that without any problem but not GPLv2 which is **terminated**!

**Comment by filips123** [comment]
No. It was suspended because it violated GitHub ToS, USA and EU laws, was spamming and trolling, making death threats to ZeroNet contributors, etc.

**Comment by George-Soros** [comment]
Threat? I was helped ZeroNet you fuck! I contributed and also I was who reported the problem with the license which is in this very moment is not exist anymore! You @imachug and @shortcutme was on rage and reported more than 15 account after that you managed to beg Microsoft to suspend @antifa. This all still don't matter to me be honest but that is very clear you are a fucking criminal fascists shit! Yes, I will and going to punch your face if I ever see you and kick the Nazi ideas out of your fucking head!

**Comment by filips123** [comment]
> I will and going to punch your face 

Yes, you certainly wasn't banned because of that...

**Comment by George-Soros** [comment]
Don't fucking need to censor GitHub, close my pull requests and copy anything from that pull request without giving credit and when I report license violations and copyright infringement you fucking need to shot your mouth and do your best to resolve the issue not attacking me and running to Microsoft to ban my account! You fucking trash! Tamas Kocsis should be hanged and will be hanged very soon! Nazi shit!

**Comment by filips123** [comment]
Yes, spamming, trolling, death threats aren't reason to ban you...

**Comment by George-Soros** [comment]
I do it for a very good reason! You fucking nazi shit along with @imachug and @shortcutme even the voting https://github.com/HelloZeroNet/ZeroNet/issues/2273 misleading previous contributors! Not a single word about my report and not a single time the fucking voting mentions why it is started! Saying ZeroNet recently informed... bla bla bullshit! You are all attacking me because I telling the truth! So fuck you!

**Comment by George-Soros** [comment]
Don't fucking violate other people licenses and not steal they contributions and code you criminal copyright infringer :hankey: ! 

How many people is misleaded right now in the voting? I tell you! Over a 100 people lied straight into the face!

**Comment by gorhgorh** [comment]
hey hey @filips123 @George-Soros can I remind you that this issue is about @rllola proposal
@George-Soros thanks for telling us a bit about some concerning issue on the project, but please refrain to settle debt on this thread ?
also @filips123 same apply this is not a battleground to defend your claims

**Comment by George-Soros** [comment]
@rllola **Can't distribute ZeroNet under the current license neither you are allowed!** It is illegal in every single country of the world!

**Comment by imachug** [comment]
Let me jump in quickly. I don't want this talk to be abandoned because of a silly flane war. Let me just note some facts:

Hacktivist (his old username) was going to contribute to ZeroNet and made a useful PR. He then added some "features" which he thought were necessary while the project owner as well as a few contributors (e.g. me) disagreed with it. We asked him to revert the useless changes (namely, enabling caching for a whole week even for Jekyll-like sites), but he didn't want to change anything. While we were arguing, he started harassing me and the project owner and the discussion quickly turned into "Why change that? - You idiot, go ** yourself!"

By this time, GitHub has noticed this behavior and banned hacktivist, but he re-registered. He started spamming our issue tracker with discussions. We were still replying politely, but almost the same story happened a few times again.

Anyways, antifa (his new name) then noticed that ZeroNet uses GPLv2 license, but a few dependencies are licensed under Apache 2.0 and one dependency is GPLv3+. We found out that it'd take some time to make GPLv2-compatible alternatives, so it'd be eaiser to switch to GPLv3. Unfortunately, the project was GPLv2-only so we would have to ask all previous contributors for their agreement.

However, antifa started telling everyone that the only possible option is to switch to GPLv3+. Please notice that quite a few people asked him what part of GPLv2 states that changing the license to non-GPLv3 is illegal but the best answer so far was "you don't know how licensing works".

When he found out that we weren't going to switch the license to GPLv3 without an agreement, he forked ZeroNet, changed its license to GPLv3 and started distributing it. By this time, I was sure that nothing good would happen so I asked him why he distributed ZeroNet under GPLv3 without my agreement (I am a contributor). His answer was

# THE LICENSE IS ABANDONED

**ZeroNet license is abandoned, it is now public domain!**

(all caps, bold and a big heading - almost a quote)

Strangely, he couldn't explain why public domain code can't be used in non-GPLv3 projects and started harnessing everyone again instead.

I was tired of this stupidity so I wanted to show that his theory doesn't work well. Namely, I asked him to remove my code from his repository. Our dialogue:

- Can you remove my code please? 
- No. 
- Why? My code was licensed under GPLv2 (because ZeroNet license was GPLv2-only) so you can't use it in a GPLv3-licensed project. 
- **ZERONET LICENSE IS ABANDONED, IT IS NOW PUBLIC DOMAIN**
- If the license is abandoned, my work can be considered proprietary. Thus you cannot use it without my agreement. Please remove my code.
- You don't know how licensing works. 
- If it is public domain, why can't we use others' previous ZeroNet code under GPLv3? 
- You nazi!.. *more garbage hidden*

I was almost sure that switching license without contributor agreement is impossible, so @krixano, @filips123 and me started a contributor license agreement issue where contributors could allow us to use their code under GPLv3-only and/or GPLv3+ and/or lax licenses (e.g. MIT). Antifa then started spamming our issue tracker and telling everyone the vote is fake and his repository is the only legal way of ZeroNet distribution.

This happened quite a long time ago (a few days). Since that time:

- I've got rid of the only GPLv3-incompatible dependency (it was licensed under BitTorrent Open Source license) by making a MIT alternative;
- I am about to finish a MIT cryptography library in case we manage to leave GPLv2;
- More than a half of the contributors voted, almost everyone supports GPLv3;
- Antifa registered at least 8 new accounts.

These are pure facts. Decide whether you want ZeroNet talk to be abandoned because of a single rude person for yourself.

**Comment by George-Soros** [comment]
I will NOT remove any library at your wishes and I told many times I release ZeroNet under GPLv3+! You going to destroy ZeroNet if you remove any code and also you did lie to all previous contributors when you misleaded them with a fucking voting which was a shitshow to github not to take down the repository!

I going to make a legal report to the Fee Software Foundation and to GitHub and initiate the full takedown of this illegal software! 

I suggest you fucking Nazi shit to fix the license immediately!

**Comment by George-Soros** [comment]
**ZERONET LOST ITS LICENSE WHEN VIOLATED OTHER PEOPLES LICENSES AND INFRINGED COPYRIGHTS!**

**THE GPLv2 TERMINATION IS INDEFINITE!** 
You can't ever use GPLv2 license!

**Comment by filips123** [comment]
> You can't ever use GPLv2 license!

So switch to MIT...

**Comment by imachug** [comment]
Can you please stop spamming *other* projects? Let's switch to IRC.

**Comment by George-Soros** [comment]
You can't fucking switch to MIT you fuck! ONce the program is on GPL you MUST keep under GPL! It is not possible to switch to anything else and we have discussed this many many times!

You are spamming other project @imachug and @filips123 I noticed the P2P community in France that ZeroNet is run by neo-Nazis and the abuse on GitHub, censorship and continues illegal activities! 

@gorhgorh Are you see how they attacking me? If I tell to anyone they violate license or that they lost the license because it is terminated than the Hungarian nazi @imachug @HelloZeroNet fast attacking me.

**Comment by filips123** [comment]
If you just said that GPL is terminated...

**Comment by George-Soros** [comment]
I need to use Internet Archive to capture this fake misleading voting what they started: https://github.com/HelloZeroNet/ZeroNet/issues/2273 They lying to all previous ZeroNet contributor! One is want to use an MIT license on it the other saying he will rewrite the libraries. 

ZeroNet LOST its license and if any library is removed I guarantee it will loose all copyrights too! I will not remove anything from the source code and so I'm legally obligated to distribute it under GPLv3+!

**Miha Štamcar** alias filips123 better you shot your mouth if you don't know what are you talking about or I make your name very very public!

**Comment by George-Soros** [comment]
@gorhgorh look at this!
@imachug said: If the license is abandoned, my work can be considered **proprietary**. Thus you cannot use it without my agreement. **Please remove my code**.

How many times I need to tell you you fuck! There is more than 1,900 fork but you only attacking me! A previously released software which used a GPL license NEVER EVER can be made proprietary! You are in some dream boy!

**Comment by filips123** [comment]
> I need to use Internet Archive to capture this fake misleading voting what they started

So you can use it as a proof that license change is doing in correct and legal way.

**Comment by filips123** [comment]
> Not possible to force 1,900 forks to remove they libraries

But it is possible to force 1,900 forks to change license?

**Comment by George-Soros** [comment]
**Nothing is correct and nothing is legal** in that @imachug @HelloZeroNet (@shortcutme) **INTENTIONALLY MISLEADING CONTRIBUTORS!** 
Nazi fcks from Hungary, Poland, Slovenia. That is ZeroNet!

**Comment by filips123** [comment]
> A previously released software which used a GPL license NEVER EVER can be made proprietary! 

If you said GPLv2 is not valid anymore...

**Comment by George-Soros** [comment]
@filips123 stop spamming! READ!

**Comment by George-Soros** [comment]
## Miha Štamcar 
You nazi shit! Shut your mouth and go back where you from! Nobody asked you to come here!

**Comment by filips123** [comment]
> Nobody asked you to come here!

Says someone who literally nobody want to be here...

**Comment by George-Soros** [comment]
I come here to warn the P2P community in France not to distribute ZeroNet without having a GPLv3 license on it!

**Comment by imachug** [comment]
@gorhgorh Anyways... I guess you'll understand there is literally no problem based on George-Soros'es replies.

**Comment by George-Soros** [comment]
There is problem! A very serious legal problem and you trying to cover up you Hungarian neo-Nazi trash! You and Tamas Kocsis should be spit on the face for violating licenses and infringing copyrights for years! Read what are you said this topic! Read it and be shameful of yourself!

**Comment by CatTheHacker** [comment]
I advise to block the further conversation in this issue and move the argument to IRC.

**Comment by George-Soros** [comment]
We don't asked you opinions @CatTheHacker maybe I call the Fedpol in Switzerland if you also join and start arguing about the license.

**Comment by CatTheHacker** [comment]
And what they will do to me? Have I violated something?
As for the licence, it has been terminated, that's a fact but for now it is prioprietary and contributors can switch licence to their choice - it has been explained to you many times.

**Comment by George-Soros** [comment]
@CatTheHacker 
>As for the licence, it has been terminated

That is very correct!

> but for now it is prioprietary

**A GPL licensed software NEVER can become proprietary!** 

I'm a contributor too just as the translators. I contributed to UiRequest.py and those changes right now are in your versionof ZeroNet. Most people anyway voted for GPLv3+ **because they using they brain and understand that Tamas Kocsis and other Hungarian Nazis posing a clear threat** to ZeroNet! @imachug more than 20 times voiced that he claims proprietary rights and I and only I should delete his code. 

If you request me to delete your code what you released under GPL than you can close the @HelloZeroNet repository and send out more than 2,000 DMCA to all those who forked it!

**Comment by filips123** [comment]
> A GPL licensed software NEVER can become proprietary!

Explain how GPLv2 statements are still true, even if the license is terminated, please.

> I'm a contributor too just as the translators.

No, you aren't.

> If you request me to delete your code what you released under GPL

He didn't agree to distribute code under GPLv3 without asking him first and only you and your fork distributed code under GPLv3.

**Comment by CatTheHacker** [comment]
If a licence is terminated, that means it couldn't be licenced under that licence, which in fact makes it unlinceced which makes it prioprietary, am I right?
Also the licence applies to the redistributed copy and not the source code itself, thus the licence can be changed, or at least that is my understanding of it.

**Comment by filips123** [comment]
> Also the licence applies to the redistributed copy and not the source code itself, thus the licence can be changed, or at least that is my understanding of it.

A license can not be changed in *current* releases of program, this is correct. E.g. you can't force people who already have an old release with the old license to change it.

However, you can change it in *new* releases. This is what would be in case of ZeroNet. In this case, you can still use old license with old release and use new license in new releases.

**Comment by George-Soros** [comment]
I just want to correct you @CatTheHacker a previously GPL licensed software can't be relicensed to anything but to GPL and even if the license is terminated that doesn't mean that the software is proprietary! Never a GPL distributed software become proprietary! **Never!**

**Comment by filips123** [comment]
Prove this.

**Comment by George-Soros** [comment]
This is even logic @filips123 just think about.

**Comment by filips123** [comment]
No it is not. Many projects already did this.

**Comment by George-Soros** [comment]
https://stackoverflow.com/questions/5419923/can-gpl-be-re-licensed

**There's no way you can rescind the GPL on the software you have already given someone. The only way that license is allowed to be changed is to a newer version of the GPL. Whoever received it as GPL will always be free to use it and redistribute it to others under the GPL.**

**Comment by George-Soros** [comment]
Painful the truth? :rofl:

**Comment by filips123** [comment]
The [link](https://stackoverflow.com/questions/5419923/can-gpl-be-re-licensed) you pasted literarry proves that you are **wrong**:

> However, if you hold the copyright on the software, you can do whatever you want with it yourself. That includes releasing it to someone else under whatever licensing terms you chose. So if you want to change a future version to be BSD, or dual-licensed, you are free to do that. If you want to sell it to some company with a closed-source license, you can do that too.

> However, as a copyright holder, you may re-license under other licenses as well, if you so please.

**Comment by George-Soros** [comment]
I'm not arguing with a retard...

**Comment by filips123** [comment]
And once again, upvoting your own comments won't make them any more truth.

**Comment by George-Soros** [comment]
![GQmQ](https://user-images.githubusercontent.com/57743911/68895690-baf2a200-0721-11ea-93eb-e387a17ff532.gif)

**Comment by CatTheHacker** [comment]
What are you writing is correct @George-Soros, we can't relicence the already released copies of ZeroNet, but we can relicence the new ones, which is what are we trying to do if you didn't interrupt us.

> 
> 
> > Also the licence applies to the redistributed copy and not the source code itself, thus the licence can be changed, or at least that is my understanding of it.
> 
> A license can not be changed in _current_ releases of program, this is correct. E.g. you can't force people who already have an old release with the old license to change it.
> 
> However, you can change it in _new_ releases. This is what would be in case of ZeroNet. In this case, you can still use old license with old release and use new license in new releases.

Yep, I fully agree and do get that, I tried to make answer as short as possible.
The released software cannot be relicenced, but future copies can be.

**Comment by George-Soros** [comment]
Good luck in destroying ZeroNet! If any other license is put on it than GPLv3 than you can already dig a hole in the cementary for ZeroNet because I will continue to work on ZeroNet if necessary even sell it using a GPLv3+ license on it!

**Comment by George-Soros** [comment]
> future copies can be

Well, you **first remove my contribution from it** because I not allow my GPL contribution to be relicensed to anything but GPL! If you don't remove my addition from the software you can't change the license in the future versions either!

**Comment by filips123** [comment]
> Well, you first remove my contribution from it because I not allow my GPL contribution to be relicensed to anything but GPL!

Well, you first show the exact lines which contain you copyrighted contribution. And once again, handling MIME types based on IANA and RFCs is not copyrighted by you.

**Comment by CatTheHacker** [comment]
> 
> 
> > future copies can be
> 
> Well, you **first remove my contribution from it** because I not allow my GPL contribution to be relicensed to anything but GPL! If you don't remove my addition from the software you can't change the license in the future versions either!

It's not that hard to replace few lines wrote by you, if they are your contributions.
Also please calm down, you are making me sad and feel worthless as a human being (which I'm not).

**Comment by George-Soros** [comment]
Don't start it again! @HelloZeroNet even stated that **his merge is based on my pull request**! Copyrighted for that matter.

**Comment by filips123** [comment]
> his merge is based on my pull request! 

Based on != Copied from
Based on PR == Based on the idea of the PR in this case

The idea in this case if handling more MIME types as IANA and RFCs specify. This is not copyrighted by you.

**Comment by George-Soros** [comment]
@CatTheHacker I like you but just because you are living in Bern and people around Bern are very respectful, intelligent and friendly! I don't know you personally but I like you because you respectful at least not like others here.

**Comment by George-Soros** [comment]
Without me ZeroNet not handling correctly the MIME types (did not handled it correctly for years!) I come and I sent a pull request which was copied, changed and included in ZeroNet without giving me credit! What this mean? You must destroy how ZeroNet handles mime types if you want to relicense future versions! Roll it back how you used it for years before of my pull request!

**Comment by filips123** [comment]
> did not handled it correctly for years!

Because nobody reported problems.

> I sent a pull request which was copied

Not to mention that you include an unnecessary cache for whole week which nobody wanted.

> You must destroy how ZeroNet handles MIME types and remove UTF-8 encoding from CSS etc if you want to relicense future versions!

Ok? So handling MIME types and using UTF-8 is copyrighted by you?

**Comment by George-Soros** [comment]
How it is included in ZeroNet is its copyrighted by me yes! Not the standard or RFCs you retard!

**Comment by George-Soros** [comment]
Nobody reported problems? I can show you here at lest 5 reports! Shout your mouth. This absolutely unrelated to the fact that ZeroNet infringes copyright and violates licenses for years! 

**I was also that person who reported this license thing!** You should be thankful!

**Comment by George-Soros** [comment]
@namazso https://github.com/namazso/SecureUxTheme :clap: Look how se added a GPLv3+ license! I would help her but I guess she is fine with this structure. See README.md and LICENSE files in her repository. That is a GPLv3+ license! :fireworks: :champagne:

**Comment by George-Soros** [comment]
@CatTheHacker 
> you are making me sad and feel worthless as a human being (which I'm not).

I'm deeply sorry if I made you feel this way! My intentions are good and I never said any bad word to you. Please forgive me. I want the best for ZeroNet and I alone need to fight and educate (mostly about law) 3-4 maniac Nazis for more than two weeks. Again, I have no problem with you at all! :hugs:

**Comment by George-Soros** [comment]
@CatTheHacker 
-----BEGIN PGP MESSAGE-----

wcFMA5h+MXkBgxuuARAAtoABjkCvNCEGkCOtWd302mstFsPydFc1l7URTz6XwD/s
xVJyvY5xn2hcAd7PHBDZkYcbwEhIk0h3BiufdtMDLoOR7qgYoTB30rT0RT8DIlwz
8deosZHkMbG+lbY4gcmtJJkiMdbawBYFyQj15XvOyLMZ3e9NMdXGOq5KGIOzCwW9
p2LEbOvEkrT4VzPyyamjSUN4JXOt4+/p/PNLLIqjo5PTuLv4SR1IYuzMSRZ9VRZs
EWXK4o9rQwerALcHTCReILlNOgp6rRhcxtm2hHoJnjDWJa8ksyVhVMGsAPUNocAP
iJtNguu8DLtxtNN42kAlYTvSNox/BYgce89xQdDZm85izPSMuoU+yvsguEcNX6nP
YWgXUbjRzij+pHk1HGmFa9kSLdFHf9Qu6H9oG2/iBWBtxWR7VaNSk11Dr0bh7zBC
22c3LbXmAT3tb3OHj5Xq/W3h+DPltvu9iV9w687sK6jKPn2XFRdulL3PtwI/vaw+
F8PwX/o2XRxVD/GezIFunTkN42guwjRM/KLM/01XP9tHb8AcD7kPeLLC26Wa3ZaU
QmLu4pPFMVOeq+DZWZRzrVprkUSRXh7dsd+qbnIuRuXtWWvsQBcDvBTzocdAtBNd
2Zy64/m/l14GegPoqSBm2ZZ/rIwvb48JTb+jzGQy/YrAoky73pyBcB3Jd3AVKoHS
wCMBc1SWq1G/keUteFTjdEchHO9w6rvgrBYcy4PsyUj9sWpm8FcNU41zrMzyR6Hl
9IbNF/fmGu1+BNyhAmc8hsg8QkaAl5Ktu7fy/jzPPIocRBcWLtyzp8JcANGmRKXA
kBm5ILXU8Tm9KY3Agc6veoQI5EFOAaeGcUhxUaYhmbUdCmXsWoHoxKnLT4juMvs/
qxpQch2huvFO7j+LDg9XIw5adzjDrh2+E6Yesud87FtIxk2h+dPfcYoy2i/ZJuQ0
zeLIOrEWvfhJr36S73tTzw+s90gaIz79ygU8Y1pAcqljDyXprw==
=wveC
-----END PGP MESSAGE-----

**Comment by namazso** [comment]
@George-Soros please don't tag me in issues i haven't contributed to, especially with offtopic posts.

And yes I am very fine with the current structure, especially since GitHub sets up the project this way if you pick a license on the website. The choice of a license was also intentional, due to existance of various nonfree "competitors" to whom I'd prefer not to give leechable code.

Also I would prefer if you used pronouns they/them/themself in the future.

**Comment by rollbackzeronet** [comment]
@gorhgorh Look at this: https://github.com/HelloZeroNet/ZeroNet/pull/2311 My pull request to remove my contribution is closed again. This (@HelloZeroNet, @imachug @filips123) are criminal copyright infringers who violating more than 3 different licenses and censoring GitHub to hide the fact that coy, attack and discredit contributors!

**Comment by Z-a-r-a-k-i** [comment]
Why do we need to have this kind of infite debate even before the presentation ?
All this just makes me even more curious about the topic !

@rllola Please don't cancel

**Comment by moul** [comment]
Thank you @rllola for this workshop :+1:

**Comment by krixano** [comment]
> also @filips123 same apply this is not a battleground to defend your claims

He has EVERY right to defend against a person who has been PROVEN to have given death threats and abuse to people online, for which he was BANNED BY GITHUB MULTIPLE TIME for, and then try to shut down a person for calling out a LIAR means that you are just as abusive as the person you are allowing to be abusive.

And this is why I am completely fed up and done with most programmer communities. Because you are all disrespectful people who continue to allow disgusting behavior like this to be promoted and shut down the people trying to defend themselves against these attacks.
