### ISSUE TITLE
[Talk Proposal] Replacing BGP in 4 easy steps

### ISSUE THREAD

**Issue by cjdelisle** [francep2p/community#67]
#### Title

Replacing BGP in 4 easy steps - The PKT long game

#### Languages

- [ ] 🇫🇷
- [x] 🇬🇧

#### Estimated duration

30-40 min

#### Required knowledge level

  
| Network      | Cryptography | Blockchain   | General Tech |
| ------------ | ------------ | ------------ | ------------ |
| [ ] None     | [ ] None     | [ ] None     | [ ] None     |
| [ ] Beginner | [x] Beginner | [x] Beginner | [x] Beginner |
| [x] Advanced | [ ] Advanced | [ ] Advanced | [ ] Advanced |
| [ ] Expert   | [ ] Expert   | [ ] Expert   | [ ] Expert   |

#### Video recording

- [ ] Yes (mandatory) 
- [x] Yes (if possible) 
- [ ] No 

---

## Description of your talk
BGP is without a doubt one of the greatest decentralized protocols ever devised, the use of friend-to-friend links, peering relationships, and filters combine to leverage human and machine capabilities in a truly unique way, and it should be required study for anyone wanting to create a decentralized protocol of their own. But our expectations of BGP are simply unreasonable: Take for example IP addresses, these are essentially virtual property and today we would never consider using anything short of a blockchain -- yet BGP is able to handle this, and it does so with near perfection. Furthermore as the internet scales, our expectations will only become more and more unreasonable.

In 1999 there were 5000 Autonomous Systems (ISPs) speaking the BGP protocol, in 2008 the number had grown to 30000, in the following ten years it would double, but in the last 2 years it grew by 50% and is over 90000 now. But still just under half of the world has no internet at all, and only 15% have what is considered "broadband".

The internet has probably been the biggest single force for individual liberation since the printing press, but in order to bring competitive access to the whole world I estimate we will need hundreds of millions of Autonomous Systems, not just hundreds of thousands. So we are in a dilemma: BGP cannot take us where we need to go, but nobody knows what will.

Here I will present the PKT project which is founded on a simple yet radical idea: What if we separated the physical role of hardware operation from the technical role of network engineering? Becoming an *infrastructure provider* would be no more difficult than pointing an antenna, and everybody would have their choice of thousands of "Virtual ISPs" who build their networks from bandwidth leased in a decentralized bandwidth market. It will be like choosing from any phone company in the world, and everyone is roaming all of the time.

Of course a project of this scope must be rolled out in steps, and I will present the steps which will go into making this a reality.

* We will start with a VPN marketplace because the very existence of VPNs represents the need for better network technology.
* Then we will enable smart internet sharing and mesh networking with the Virtual ISP service to optimize those networks.
* Then we will tokenize bandwidth so that we can establish a true decentralized bandwidth market.
* Then we will begin developing high capacity routing hardware to take the network back to the datacenter.

---

## About you

* Name: Caleb James DeLisle
* Matrix handle: @cjdelisle:m.trnsz.com
* Other contact info: cjd.cjdns@fr

**Comment by artrepreneur** [comment]
Great summary of the project plan, generally speaking. The problem is illustrated effectively, but I don't think a specific solution is proposed, rather the steps necessary to foster the right environment for a solution. At a high level, surely decentralization is that solution, but routing strategies will vary. This a great experiment because we will see if capitalism, ie. the free market, can solve this problem. This is a question mark for me because one of the key flaws of capitalism is the rise of monopolies which tend to act as a centralizing agent. However, if it does serve as an impetus to solving this problem, then it makes a good argument for capitalism as an agent of efficiency, thus satisfying the efficient market hypothesis. Other projects I've seen in this space tend to not have as many milestones in their plan. They tend to think they can sell networking hardware to enough people to spin up some kind of network. But, node density is clearly and issue for most, because they tend to be short on value proposition and market reach. Perhaps the VPN marketplace is the growth hack these networks need to reach a larger scale, because the general public isn't aware of what BGP is or what it's problems might be. But, these days, VPN's seem to be trending, so it's a smart play to go that way. 'Nuff said.

**Comment by moul** [comment]
Will take place during the next Paris P2P event in march (#51)

Thank you :)

**Comment by cjdelisle** [comment]
Thank *you* :)

**Comment by cjdelisle** [comment]
Going to close this issue to clear it from my notifications, thanks for a great time !
